app:
  name: @project.artifactId@
  version: @project.version@

server:
  port: 8080
  compression:
    enabled: true
  forward-headers-strategy: framework
  shutdown: graceful
  servlet:
    session:
      cookie:
        http-only: true
        secure: true
    encoding:
      enabled: true
      charset: UTF-8
  undertow:
    url-charset: UTF-8

provider:
  keycloak:
    url: http://localhost:7080
    realm: access-pilot
    client-id: accesspilot-backend
    client-secret: b0h3gPFmK79ZwcZcvZkKQPHfjNerywqV
    ignore-clients:
      - realm-management
      - broker
      - security-admin-console
      - account
      - admin-cli
      - account-console

identity:
  provider: keycloak

jwt:
  auth:
    converter:
      resource-id: accesspilot-backend
      principal-attribute: preferred_username

cors:
  allowed-headers: '*'
  allowed-methods: 'GET,POST,PUT,PATCH,DELETE,OPTIONS'
  allow-credentials: true
  max-age: 3600
  allowed-origin-pattern: 'http://localhost:*,localhost:*,https://exemplo-arquitetura.dev.getinsight.tech'

feign:
  log-level: full
  client:
    keycloak:
      url: ${provider.keycloak.url}/admin/realms/${provider.keycloak.realm}

email-notification:
  approver:
    subject: Aprovação de solicitação
  status-request:
    subject: Status da solicitação de perfil
  url:
    hint: AccessPilot frontend
    client-url: http://localhost:8080/swagger-ui.html
    frontend-url: http://localhost:9080

spring:
  application:
    name: ${app.name:accesspilot-backend}

  main:
    lazy-initialization: true
    allow-bean-definition-overriding: true
    cloud-platform: kubernetes

  docker:
    compose:
      enabled: true
      lifecycle-management: start_and_stop
      file: ./etc/docker-compose.yaml

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${provider.keycloak.url}/realms/${provider.keycloak.realm}
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
        opaquetoken:
          client-id: ${jwt.auth.converter.resource-id}
          client-secret: ${provider.keycloak.client-secret}
          introspection-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/token/introspect
      client:
        provider:
          keycloak:
            issuer-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}
            user-name-attribute: ${jwt.auth.converter.principal-attribute}
        registration:
          registration-keycloak:
            provider: keycloak
            client-id: ${jwt.auth.converter.resource-id}
            client-secret: ${spring.security.oauth2.resourceserver.opaquetoken.client-secret}
            authorization-grant-type: client_credentials

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

  jackson:
    default-property-inclusion: non-empty
    deserialization:
      fail-on-unknown-properties: false
    locale: pt_BR
    time-zone: America/Sao_Paulo

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    hikari:
      auto-commit: false
      connection-init-sql: SELECT 1;
      connection-test-query: SELECT 1;
      minimum-idle: 1
      maximum-pool-size: 10
      connection-timeout: 30000
      idle-timeout: 60000
      leakDetectionThreshold: 10000
      isolate-internal-queries: true

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    open-in-view: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        envers:
          audit_table_suffix: _AUD
          store_data_at_delete: true
          revision_field_name: REV
          revision_type_field_name: REVTYPE

  liquibase:
    enabled: true
    change-log: classpath:db/changelog-master.xml
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}


  mail:
    protocol: ${MAIL_PROTOCOL:smtp}
    host: ${MAIL_HOST:smtp-legacy.office365.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            enable: false
        from: ${MAIL_FROM:noreply@getinsight.it}
    test-connection: true

  cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 6379

minio:
  endpoint: http://localhost:9002
  accessKey: admin
  secretKey: abc12345
  buckets:
    - private-getinsight-accesspilot-docs
    - private-getinsight-accesspilot-emails


sentry:
  enabled: ${SENTRY_ENABLED:true}
  environment: localhost
  dsn: https://9f4bb7a60c929d10934cb1734f7bf2d5@sentry.getinsight.tech/4
  traces-sample-rate: 1.0
  enable-uncaught-exception-handler: true
  attach-stacktrace: true
  attach-server-name: true
  attach-threads: true
  enable-deduplication: true
  enable-app-start-profiling: true
  logging:
    enabled: true


springdoc:
  swagger-ui:
    enabled: true
    default-model-expand-depth: 0
    doc-expansion: none
    disable-swagger-default-url: true
    display-request-duration: true
    oauth:
      authorization-url: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/auth
      token-url: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/token
      client-id: ${jwt.auth.converter.resource-id}
      client-secret: ${spring.security.oauth2.resourceserver.opaquetoken.client-secret}
      realm: ${provider.keycloak.realm}
      scopes:
        - openid
    csrf:
      enabled: false
    show-extensions: true
    show-common-extensions: true
    syntax-highlight:
      theme: monokai
  show-actuator: false
  writer-with-default-pretty-printer: true
  api-docs:
    groups:
      enabled: true
    resolve-schema-properties: true
    enabled: true
  paths-to-exclude:
    - /error

management:
  endpoint:
    mappings:
      enabled: true
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    git:
      mode: full

logging:
  level:
    root: info

resilience4j:
  circuitbreaker:
    instances:
      keycloak:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 10s
        failureRateThreshold: 50
        slowCallRateThreshold: 100
        slowCallDurationThreshold: 2s

  retry:
    instances:
      keycloak:
        maxAttempts: 3
        waitDuration: 500ms
        exponentialBackoffMultiplier: 2
        enable-exponential-backoff: true


level-client:
  timeout:
    connect-ms: 10000
    read-ms: 30000
  retry:
    enabled: true
    period-ms: 100
    max-period-ms: 1000
    max-attempts: 2
  cache:
    max-entries: 20

