spring:
    mail:
        protocol: ${MAIL_PROTOCOL:smtp}
        port: ${MAIL_PORT:1025}
        host: ${MAIL_HOST:localhost}
        properties:
            mail:
                from: ${MAIL_FROM:no-reply@localhost}
                smtp:
                    auth: false
                    starttls:
                        enable: false
        test-connection: true
