select id,
       name,
       description,
       icon,
       authority,
       redirect_url,
       client_id,
       response_type,
       scope,
       post_logout_redirect_uri,
       start_checksession,
       silent_renew,
       startup_route,
       forbidden_route,
       unauthorized_route,
       log_level,
       max_id_token_iat_offset_allowed_in_seconds,
       history_cleanup_off
       data_criacao,
       data_atualizacao,
       criado_por,
       atualizado_por
from tb_configuration;
