name: ci-cd.yml
on:
  push:
    branches:
      - develop

jobs:

  build:
    name: build
    environment: dev
    runs-on: ubuntu-latest
    outputs:
      jar: ${{ steps.mvn-build.outputs }}
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: mvn-build
        env:
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
        run: |
          mvn -B clean package -P sentry -T $(nproc) -Dmaven.artifact.threads=$(nproc) -s maven-settings-gh.xml
          cp target/*.jar $GITHUB_OUTPUT



  container:
    name: container
    environment: dev
    runs-on: ubuntu-latest
    needs: build
    steps:

      - uses: docker/login-action@v3
        with:
          registry: registry.gitlab.com
          username: token
          password: ${{ secrets.GITLAB_TOKEN }}

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: build-image
        env:
          DOCKER_TAG: ghcr.io/${{ env.GITHUB_REPOSITORY }}:latest
        run: |
          cd
          docker buildx create --use --driver docker-container --bootstrap
          docker buildx build --platform linux/amd64,linux/arm64 -f Dockerfile -t "$DOCKER_TAG" --push .

